import {
  key,
  unique,
  KEY_SERVER_CONFIG_MEDIUMS,
  KEY_SERVER_CONFIG_MEDIUM_ID,
  KEY_SERVER_CONFIG_TITLES,
  KEY_SERVER_CONFIG_TITLE_ID,
  KEY_SERVER_CONFIG_TITLE_NAME,
  KEY_SERVER_CONFIG_TITLE_MEDIUM,
  KEY_SERVER_CONFIG_LOGS,
  KEY_SERVER_CONFIG_LOG_TITLE,
  KEY_SERVER_CONFIG_LOG_RATING,
  KEY_SERVER_CONFIG_RESOURCE_ID,
  KEY_SERVER_CONFIG_RESOURCES,
  KEY_SERVER_DATA_MEDIUM_VALUE,
  KEY_SERVER_CONFIG_MEDIUM_VALUE,
  KEY_SERVER_DATA_MEDIUM_ID,
  KEY_SERVER_PAGE_SERIES_MEDIUMS,
  KEY_SERVER_PAGE_SERIES_RESOURCES,
  KEY_SERVER_DATA_RESOURCE_ID,
  KEY_SERVER_DATA_RESOURCE_VALUE,
  KEY_SERVER_CONFIG_RESOURCE_VALUE,
  KEY_SERVER_PAGE_SERIES_TITLES,
  KEY_SERVER_DATA_TITLE_ID,
  KEY_SERVER_DATA_TITLE_NAME,
  KEY_SERVER_DATA_TITLE_MEDIUM,
  KEY_SERVER_DATA_TITLE_LINKS,
  KEY_SERVER_CONFIG_LINKS,
  KEY_SERVER_CONFIG_LINK_TITLE,
  KEY_SERVER_DATA_TITLE_LINK_RESOURCE,
  KEY_SERVER_CONFIG_LINK_RESOURCE,
  KEY_SERVER_DATA_TITLE_LINK_RESOURCE_ANIDB_ID,
  KEY_SERVER_CONFIG_LINK_RESOURCE_ANIDB_ID,
  KEY_SERVER_PAGE_SERIES_LOGS,
  KEY_SERVER_DATA_LOG_TITLE,
  KEY_SERVER_DATA_LOG_RATING,
  KEY_SERVER_DATA_TITLE_LINK_RESOURCE_MANGAUPDATES_ID,
  KEY_SERVER_CONFIG_LINK_RESOURCE_MANGAUPDATES_ID,
  KEY_SERVER_DATA_TITLE_LINK_RESOURCE_NOVELUPDATES_SLUG,
  KEY_SERVER_CONFIG_LINK_RESOURCE_NOVELUPDATES_SLUG,
  KEY_SERVER_DATA_TITLE_LINK_RESOURCE_MYDRAMALIST_ID,
  KEY_SERVER_CONFIG_LINK_RESOURCE_MYDRAMALIST_ID,
} from "$lib/index";
import data from "$lib/assets/data.toml?raw";
import toml from "smol-toml";
import * as R from "ramda";

const parseData = R.once(data => toml.parse(data));

function logTitle(titles, log) {
  return titles[log[KEY_SERVER_CONFIG_LOG_TITLE]];
}

function titleMedium(mediums, title) {
  return mediums[title[KEY_SERVER_DATA_TITLE_MEDIUM]];
}

/** @type {import('./$types').PageServerLoad]} */
export function load(event) {
  const d = parseData(data);
  const mediums = key(
    R.prop(KEY_SERVER_DATA_MEDIUM_ID),
    d[KEY_SERVER_CONFIG_MEDIUMS].map((medium) => ({
      [KEY_SERVER_DATA_MEDIUM_ID]: medium[KEY_SERVER_CONFIG_MEDIUM_ID],
      [KEY_SERVER_DATA_MEDIUM_VALUE]: medium[KEY_SERVER_CONFIG_MEDIUM_VALUE],
    })),
  );

  const titles = key(
    R.prop(KEY_SERVER_DATA_TITLE_ID),
    d[KEY_SERVER_CONFIG_TITLES].map((title) => {
      const id = title[KEY_SERVER_CONFIG_TITLE_ID];

      return {
        [KEY_SERVER_DATA_TITLE_ID]: id,
        [KEY_SERVER_DATA_TITLE_NAME]: title[KEY_SERVER_CONFIG_TITLE_NAME],
        [KEY_SERVER_DATA_TITLE_MEDIUM]: title[KEY_SERVER_CONFIG_TITLE_MEDIUM],
        [KEY_SERVER_DATA_TITLE_LINKS]: d[KEY_SERVER_CONFIG_LINKS]
          .filter((link) => link[KEY_SERVER_CONFIG_LINK_TITLE] == id)
          .map((link) => ({
            [KEY_SERVER_DATA_TITLE_LINK_RESOURCE]: link[KEY_SERVER_CONFIG_LINK_RESOURCE],
            [KEY_SERVER_DATA_TITLE_LINK_RESOURCE_ANIDB_ID]: link[KEY_SERVER_CONFIG_LINK_RESOURCE_ANIDB_ID],
            [KEY_SERVER_DATA_TITLE_LINK_RESOURCE_MANGAUPDATES_ID]: link[KEY_SERVER_CONFIG_LINK_RESOURCE_MANGAUPDATES_ID],
            [KEY_SERVER_DATA_TITLE_LINK_RESOURCE_NOVELUPDATES_SLUG]: link[KEY_SERVER_CONFIG_LINK_RESOURCE_NOVELUPDATES_SLUG],
            [KEY_SERVER_DATA_TITLE_LINK_RESOURCE_MYDRAMALIST_ID]: link[KEY_SERVER_CONFIG_LINK_RESOURCE_MYDRAMALIST_ID],
          })),
      };
    }),
  );

  return {
    [KEY_SERVER_PAGE_SERIES_MEDIUMS]: mediums,
    [KEY_SERVER_PAGE_SERIES_RESOURCES]: key(
      R.prop(KEY_SERVER_DATA_RESOURCE_ID),
      d[KEY_SERVER_CONFIG_RESOURCES].map((resource) => ({
        [KEY_SERVER_DATA_RESOURCE_ID]: resource[KEY_SERVER_CONFIG_RESOURCE_ID],
        [KEY_SERVER_DATA_RESOURCE_VALUE]: resource[KEY_SERVER_CONFIG_RESOURCE_VALUE],
      })),
    ),
    [KEY_SERVER_PAGE_SERIES_TITLES]: titles,
    [KEY_SERVER_PAGE_SERIES_LOGS]: unique(R.prop(KEY_SERVER_CONFIG_LOG_TITLE), d[KEY_SERVER_CONFIG_LOGS].toReversed())
      .sort((a, b) =>
        b[KEY_SERVER_CONFIG_LOG_RATING] - a[KEY_SERVER_CONFIG_LOG_RATING]
        || logTitle(titles, a)[KEY_SERVER_DATA_TITLE_NAME].localeCompare(logTitle(titles, b)[KEY_SERVER_DATA_TITLE_NAME])
        || titleMedium(mediums, logTitle(titles, a))[KEY_SERVER_DATA_MEDIUM_VALUE] - titleMedium(mediums, logTitle(titles, b))[KEY_SERVER_DATA_MEDIUM_VALUE]
      )
      .map((log) => ({
        [KEY_SERVER_DATA_LOG_TITLE]: log[KEY_SERVER_CONFIG_LOG_TITLE],
        [KEY_SERVER_DATA_LOG_RATING]: log[KEY_SERVER_CONFIG_LOG_RATING],
      })),
   };
}
